In [1]:
import torch

In [7]:
composite_rules_path = "../results/fuzzy_gat_Composite-k16/fuzzy_rules.pt"
composite_fuzzy_params_path = "../results/fuzzy_gat_Composite-k16/fuzzy_params.pt"

composite_rules = torch.load(composite_rules_path)
composite_fuzzy_params = torch.load(composite_fuzzy_params_path)

In [9]:
composite_rules.size()
composite_rules

tensor([[3.2444e-01, 0.0000e+00, 7.7095e-41, 3.0170e-03, 1.5649e-37, 1.8277e-05],
        [1.5421e-01, 4.5142e-06, 0.0000e+00, 4.6315e-12, 6.1843e-04, 3.1065e-03],
        [5.4116e-04, 1.1122e-05, 0.0000e+00, 2.5189e-02, 2.2193e-01, 5.5800e-01],
        ...,
        [2.4555e-12, 0.0000e+00, 2.0447e-01, 1.0576e-02, 0.0000e+00, 1.9705e-26],
        [2.2672e-01, 1.4890e-06, 0.0000e+00, 3.9715e-02, 3.5710e-04, 2.5382e-03],
        [6.1908e-03, 1.2994e-10, 0.0000e+00, 4.5906e-01, 5.0992e-02, 3.4185e-01]])

In [8]:
composite_fuzzy_params

{'centers': Parameter containing:
 tensor([[-0.0863,  0.3162, -1.2391,  0.0325, -0.0863, -0.0311],
         [ 3.6064, -0.2669,  0.4961,  3.0668,  3.6064,  0.5547],
         [-0.5027,  0.7988,  1.8906, -0.8316, -0.5027, -2.3859],
         [-0.5302, -0.3955,  0.6619, -0.6816, -0.5302, -0.1034],
         [ 1.1843,  0.1387,  0.5373,  1.1819,  1.1843,  0.5296],
         [-0.0410,  0.7650,  0.4743,  0.1521, -0.0410,  0.4690]],
        requires_grad=True),
 'sigmas': Parameter containing:
 tensor([[ 0.0209,  0.4831, -0.6512,  0.1452,  0.0209, -0.2956],
         [ 0.8158, -0.3758, -0.5351,  1.1131,  0.8158, -3.9645],
         [-0.3707,  1.0652,  0.0953, -4.7044, -0.3707,  0.9129],
         [ 0.0532,  0.5040, -0.2814, -1.0776,  0.0532,  0.5694],
         [ 0.3785,  0.1955, -0.6257,  0.7199,  0.3785, -2.8232],
         [-0.0562,  0.4874, -0.6025,  0.2302, -0.0562, -0.9853]],
        requires_grad=True),
 'rule_weights': Parameter containing:
 tensor([1.5352, 1.1272, 1.1290, 1.6321, 1.4430, 1.572

In [ ]:
composite_paper_rule = torch.load("../results/fuzzy_paper_gcn_Composite-k16/fuzzy_rules.pt")
composite_paper_params = torch.load("../results/fuzzy_paper_gcn_Composite-k16/fuzzy_params.pt")


composite_paper_params

{'theta': Parameter containing:
 tensor([-0.1661, -0.1628, -0.1884, -0.1774, -0.1074, -0.2268],
        requires_grad=True),
 'alpha': Parameter containing:
 tensor([0.3875, 0.4594, 1.2951, 0.3514, 0.7650, 0.6655], requires_grad=True)}

In [14]:
composite_paper_rule

tensor([[0.5188, 0.4396, 0.1383, 0.4538, 0.5258, 0.5103],
        [0.5188, 0.8071, 0.2087, 0.6342, 0.5258, 0.6302],
        [0.5188, 0.5730, 0.7046, 0.5561, 0.5258, 0.6167],
        ...,
        [0.4015, 0.6919, 0.9500, 0.4333, 0.3031, 0.0952],
        [0.4330, 0.3267, 0.1829, 0.4476, 0.3595, 0.5951],
        [0.5188, 0.3649, 0.6736, 0.4658, 0.5258, 0.6128]])